name: "Build"
on: [pull_request]

jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        platform:
           - { os: linux, arch: amd64 }
           - { os: linux, arch: arm64 }

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Find required go version
      id: go-version
      run: |
        set -euxo pipefail
        echo "::set-output name=version::$(grep '^go ' go.mod | awk '{print $2}')"
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ steps.go-version.outputs.version }}
      id: go

    - name: Test
      run: |
        cd ./cluster-autoscaler
        GOOS=${{ matrix.platform.os }} GOARCH=${{ matrix.platform.arch }} go test -v ./cloudprovider/juju/